# frozen_string_literal: true

require "rouge"

module HunkReviewChanges
  # Generates the syntax-highlighting CSS shipped in app.css. Kept out of the request
  # path: `rake css` renders it once at build time so the running server only reads a
  # static file. Two themes are emitted under the same `.highlight` scope; the dark one
  # is wrapped in a prefers-color-scheme media query so the page follows the OS setting
  # with no toggle and no JavaScript.
  module Assets
    LIGHT_THEME = "github"
    DARK_THEME = "github.dark"

    module_function

    def rouge_css
      light = Rouge::Theme.find(LIGHT_THEME).new(scope: ".highlight").render
      dark = Rouge::Theme.find(DARK_THEME).new(scope: ".highlight").render
      <<~CSS
        /* Syntax highlighting — generated by `rake css` from Rouge themes. */
        #{light}
        @media (prefers-color-scheme: dark) {
        #{indent(dark)}
        }
      CSS
    end

    def indent(text, spaces = 2)
      pad = " " * spaces
      text.each_line.map { |line| line.strip.empty? ? line : "#{pad}#{line}" }.join
    end
  end
end
